name: Generate packages and publish
on:
  workflow_dispatch:
    inputs:        
      bumpType:
        description: 'Use a custom bump type'
        type: choice
        default: none
        options:
          - none
          - graduate
          - major
          - minor
          - patch  
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write
  
env:
  BUMP_TYPE: ${{ inputs.bumpType != 'none' && format('--bump-type {0}', inputs.bumpType) || '' }}

jobs:
  Build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: yarn

      - name: Bump
        run: yarn gitversion bump $BUMP_TYPE

      - name: Publish
        run: yarn gitversion publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}



